#program1
name=input("enter your name:")
branch=input("please tell your branch:")
gender=input("your gender is:")
college=input("from which college you are?")
age=int(input("enter your age"))
print("name:",name)
print("branch:",branch)
print("gender:",gender)
print("college:",college)
print("age:",age)
